kind: Model
apiVersion: v1alpha4
metadata:
  displayName: NISMOD - Transport (model v2.3.0 build 6)
  name: nismod-transport-standalone
  summary: National Infrastructure Systems Model - Transport, standalone
  type: transport
  source_code: https://github.com/nismod/transport
  description: >
    NISMOD v2 Transport Model is a national-scale (Great Britain) transport model
    developed to support policy making regarding the future infrastructure. It
    forecasts the impact of various endogenous and exogenous factors on transport
    demand and capacity utilisation, following an elasticity-based simulation
    methodology. The model consists of three submodels covering the following modes
    of transport: road (passenger and freight vehicle flows), rail (total station
    usage), and air (domestic and international passenger movements).

    This configuration runs only the core transport model, without the smif
    model coupling wrapper which is used in the integrated NISMOD set-up.

    Source code: https://github.com/nismod/transport
    Documentation: https://nt2.readthedocs.io/en/latest/
spec:
  inputs:
    env:
      - name: ARGS
        title: Arguments
        desc: >
          Provide command line argument string. Config file path should be
          relative to /data directory
        type: string
        default: -c ./inputs/config/config.properties -b
      - name: JAVA_OPTS
        title: Java options
        desc: Java VM configuration
        type: string
        default: "-XX:+UseContainerSupport -XX:MinRAMPercentage=20.0 -XX:MaxRAMPercentage=90.0"
    dataslots:
      - name: Config
        description: >
          Model config.properties file or files
        default:
          - uid: 65d2e04c-9530-4303-9a1d-0454fbdd2ba4
            versionUid: 855ec6c1-6390-486a-9d48-f934baba81cb
        path: inputs/config
        required: true
      - name: CSV files
        description: >
          Scenarios and parameter tables
        default:
          - uid: a67a6179-1ca2-4283-9db5-0bf7aa52d8ef
            versionUid: e0b0e408-401b-42e0-8269-4c5ada2b56d6
        path: inputs/csvfiles
        required: true
      - name: Disruptions
        description: >
          Simulated link disruptions
        default:
          - uid: 906f677b-4d50-4e5c-83af-ffae9c57b2e1
            versionUid: 859bb660-287b-474c-a366-f8713b730062
        path: inputs/disruptions
        required: false
      - name: Interventions
        description: >
          Modelled options to simulate as interventions in the network
        default:
          - uid: e56689c7-3e8f-42a7-8ed7-ead262e808a6
            versionUid: 6405c09e-af1f-4292-a4d7-a50b3f9ea3b8
        path: inputs/interventions
        required: true
      - name: Routes
        description: >
          Pre-calculated route options
        default:
          - uid: 1232a2c7-8b00-48c1-8b69-25d7141bf854
            versionUid: 13970367-ab0b-4f6a-824f-38754248936f
        path: inputs/routes
        required: false
      - name: ShapeFiles
        description: >
          Network and zone definitions
        default:
          - uid: 7a39057a-50fb-4045-a45b-93bf29814b06
            versionUid: c9468b87-25d2-4c6f-99ce-a3b337be3efc
        path: inputs/shapefiles
        required: true
